<a href="https://colab.research.google.com/github/sonudk/Source-Code-from-Tutorials/blob/master/first_attempt_mnist_mln.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification of handwritten digits using Multi Layered Network

# MNIST Dataset

<img src="https://upload.wikimedia.org/wikipedia/commons/2/27/MnistExamples.png" title="MNIST dataset" align="center"/>



# Problem
Classify handwritten digits from 0 - 9. <br>
Each image is 28x28 pixels

<img src="https://corochann.com/wp-content/uploads/2017/02/mnist_plot.png" title="" align="center"/>


# Understanding the data

In [1]:
# MNIST data is present in the keras library. Load the data using load_data function of mnist
# Load the data into 4 variables - train_samples, train_labels, test_samples, test_labels
from keras.datasets import mnist
print(type(mnist))
(train_samples, train_labels) ,(test_samples, test_labels) = mnist.load_data()
import sklearn
from sklearn.model_selection import train_test_split


Using TensorFlow backend.


<class 'module'>
11493376/11490434 [==============================] - 1s 0us/step


### Shape of Data

In [2]:
## Print and observe the shapes of the 4 variables - train_samples, train_labels, test_samples, test_labels
print(train_samples.shape)
print(test_samples.shape)
print(train_labels.shape)
print(test_labels.shape)
#Your code here

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


### Range of Values
Look at the range of values

In [3]:
import numpy as np
### Print max value of samples in train_samples

# Your code here
#print(train_samples[train_samples.argmax()])

print(np.amax(train_samples))

255


In [4]:
### Print min values of samples in train_samples

#Your code here
#print(train_samples[train_samples.argmin()])
print(np.amin(train_samples))# this is the way to get max element using numpy you also can write code for this


0


# Data Preparation

### Normalize inputs to (0, 1)

In [5]:
# Convert data type of elements in train_samples and test_samples from uint8 to float32

#Your Code here

'''
print(np.ndarray.__bases__)

for i in range(28):
  for j in range(28):
    train_samples[i][j]=float(train_samples[i][j])
    
#train_samples=float(train_samples)
train_samples.astype(float)
for i in range(28):
  for j in range(28):
    train_samples[i][j]=train_samples[i][j].astype(float)
print()
print(type(train_samples))
print(train_samples)print(train_samples.shape)
print(train_samples[2])'''

train_samples= np.ndarray.astype(train_samples,dtype=float)
test_samples= np.ndarray.astype(test_samples,dtype=float)

print(type(train_samples))
train_samples_max=np.amax(train_samples)



<class 'numpy.ndarray'>


In [6]:
# Normalize inputs to (0,1)
# Divide train_samples and test_samples by max value of train_samples

#Your code here
# now the data type is float so we get float by using 255.0
train_samples=train_samples/train_samples_max
test_samples=test_samples/train_samples_max
print(test_samples.shape)
#print(test_samples[289])



(10000, 28, 28)


### Convert outputs to 1-hot vectors

In [7]:
# convert train_labels and test_labels to 1-hot encoding

#Your code here
'''print(test_labels)
print(len(test_labels))
print(test_labels.shape)

print(train_labels)
print(train_labels.shape)
print(train_labels[234])


train_labels_oneHot=np.zeros((10000,10))
for i in range(10000):
  train_labels_oneHot[i,train_labels[0,i]]=1
print(train_labels)'''

print(train_labels)
print(train_labels.shape)
train_labels_oneHot=np.zeros((60000,10))
for i in range(60000):
  train_labels_oneHot[i,train_labels[i]]=1
print(train_labels_oneHot.shape)
test_labels_oneHot=np.zeros((10000,10))
for i in range(10000):
  test_labels_oneHot[i,test_labels[i]]=1
print(test_labels_oneHot.shape)
'''print(train_labels[2])
print(train_labels_oneHot[2])
#for i in range(60000):
assert np.all(train_labels_oneHot==train_labels)'''
# to insure things are smooth we have to cross check

[5 0 4 ... 5 6 8]
(60000,)
(60000, 10)
(10000, 10)


'print(train_labels[2])\nprint(train_labels_oneHot[2])\n#for i in range(60000):\nassert np.all(train_labels_oneHot==train_labels)'

# Network Architecture

In [8]:

## Input is currently in the shape (samples, height, width)
## Reshape it such that it is suitable to be fed into a feed forward network
## hint - shape should be (samples, ?)

# Your code here
print(test_samples.shape)
train_samples=train_samples.transpose(2,0,1).reshape(60000,-1)
print(train_samples.shape)
test_samples=test_samples.transpose(2,0,1).reshape(10000,-1)
print(test_samples.shape)



(10000, 28, 28)
(60000, 784)
(10000, 784)


In [9]:
# Layer definitions

##Create a multi-layered neural network
## 1st hidden layer with 512 neurons and 'relu' activation
## 2nd hidden layer with 256 neurons and 'relu' activation
## Output layer with softmax activation
### Use Adam optimizer of keras
### Categorical cross entropy is loss

# Your code here
from keras.layers import Input, Dense
from keras.models import Sequential
from keras import optimizers
model=Sequential()
model.add(Dense(512,input_dim=784,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(10,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


Instructions for updating:
Colocations handled automatically by placer.


In [10]:
### Print summary of model and check if it is as desired. Also check total number of parameters to be trained.

#Your code here
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


In [11]:
### Fit the model on train samples. Play with different values of epochs and batch_size. 
### See which gives the optimal result in the least amount of time.
model.fit(train_samples,train_labels_oneHot,epochs=20,batch_size=1000)


Instructions for updating:
Use tf.cast instead.
Epoch 1/20
60000/60000 [==============================] - 4s 60us/step - loss: 2.3089 - acc: 0.1059
Epoch 2/20
60000/60000 [==============================] - 4s 61us/step - loss: 2.2919 - acc: 0.1276
Epoch 3/20
60000/60000 [==============================] - 4s 60us/step - loss: 2.2736 - acc: 0.1470
Epoch 4/20
60000/60000 [==============================] - 4s 60us/step - loss: 2.2398 - acc: 0.1728
Epoch 5/20
60000/60000 [==============================] - 4s 61us/step - loss: 2.1808 - acc: 0.2057
Epoch 6/20
60000/60000 [==============================] - 4s 60us/step - loss: 2.0898 - acc: 0.2510
Epoch 7/20
60000/60000 [==============================] - 4s 60us/step - loss: 1.9635 - acc: 0.3038
Epoch 8/20
60000/60000 [==============================] - 4s 61us/step - loss: 1.8184 - acc: 0.3612
Epoch 9/20
60000/60000 [==============================] - 4s 60us/step - loss: 1.6602 - acc: 0.4215
Epoch 10/20
60000/60000 [===========================

In [17]:
##Evaluate the model on test samples and print accuracy
# why with batch size accuracy increase and with epochs Increases that is easy to get
# Your code here
# in above epochs case why accuracy is decreasing in each epoch
loss,accuracy=model.evaluate(test_samples,test_labels_oneHot,verbose=0)
import sklearn
from sklearn.metrics import confusion_matrix
predict_labels=model.predict(test_samples)
print(predict_labels.shape)
'''predict_labels_oneHot=np.zeros((10000,10))
for i in range(10000):
  predict_labels_oneHot[i,predict_labels[i]]=1
print(predict_labels_oneHot.shape)'''
print(test_labels_oneHot.shape)
m=confusion_matrix(test_labels_oneHot.argmax(axis=1),predict_labels.argmax(axis=1))


(10000, 10)
(10000, 10)


In [19]:
### Print confusion matrix

# Your code here
print(m)
print('accuracy of model:%0.4f'%accuracy)

[[ 73  61  83  71 101  63  75 282  83  88]
 [ 75  80  90  68 148  81  72 337  98  86]
 [ 64  81  91  75 105  70  68 302  99  77]
 [ 74  72  86  62  88  64  67 315 106  76]
 [ 77  68  84  68  84  53  81 302  87  78]
 [ 47  70  72  57  99  48  78 261  91  69]
 [ 93  79  77  56 109  50  74 251  92  77]
 [ 74  83  78  83  88  48  70 310  97  97]
 [ 88  79  79  59 106  56  72 290  82  63]
 [ 90  69  96  73 128  68  53 276  77  79]]
accuracy of model:0.0983
