<a href="https://colab.research.google.com/github/sonudk/Source-Code-from-Tutorials/blob/master/Iris_Assignment_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import Iris Dataset

In [0]:
import sklearn
from sklearn.datasets import load_iris
import numpy as np
import keras
np.random.seed(10)

iris = load_iris()

### Data Exploration

In [97]:
## Print type of iris
print(type(iris))

<class 'sklearn.utils.Bunch'>


In [98]:
## Print parent classes of this type
## Use the attribute __bases__ of the type that you have found
print(sklearn.utils.Bunch.__bases__)

(<class 'dict'>,)


So, you must have found that iris is a dict object

In [99]:
## Print the keys present in iris
print(iris.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [100]:
## Create X and Y variables. X is the input features, Y is the output labels
X=iris.data
Y=iris.target
print(X)
print(Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [101]:
## Track 5 random samples
isamples = np.random.randint(len(Y), size = (5))
print(isamples)

[  9 125  15  64 113]


In [102]:
#Shape of Data
print(iris.data.shape)
#print shape of X and Y
print(X.shape)
print(Y.shape)

(150, 4)
(150, 4)
(150,)


### Preprocess Data

#### Convert Labels(Y) to one-hot encoding 

In [103]:
### Convert Y to 1-hot encoding

##Your Code Here
Yp=np.zeros((150,3))
for i in range(150):
  Yp[i,Y[i]] = 1

print(Yp)

    
# Look at converted Y for the random samples we are tracking
  
print(Yp[isamples],Y[isamples])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.



```
`# This is formatted as code`
```

### Its time to split your model into training and testing samples 

In [104]:
### split the data into 80% training and 20% testing 
### Split X into two variables X_train and X_test
### Split Y correspondingly into two variables Y_train and Y_test

### Your Code Here
import sklearn
import pandas as pd
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
X_train,X_test,Yp_train,Yp_test=train_test_split(X,Yp,test_size=0.2)
print(X_train.shape,X_test.shape)
print(Yp_train.shape,Yp_test.shape)

(120, 4) (30, 4)
(120, 3) (30, 3)


### Data Normalization/Scaling


In [0]:
### Normalize data to be of zero mean and unit variance
def findstdmean(X):
  mean=np.sum(X,axis=0)/X.shape[0]
  X1=X-mean
  std=np.sqrt(np.sum(X1*X1))/X.shape[0]
  return mean,std
def normalizedX(X,mean,std):
  return (X-mean)/(std+1e-8)

mean_train,std_train=findstdmean(X_train)
X_train=normalizedX(X_train,mean_train,std_train)

Note: If the first 5 samples of X_train and Y_train looks like the one given below
then congratulations! You are on the right track;
If not, then persistance is the key to success :)


In [137]:
## Print and observe the normalized inputs and compare with older inputs
iris_panda=pd.DataFrame(iris.data,columns=iris.feature_names)
iris_panda.head()
  

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [138]:
  
X_train_panda=pd.DataFrame(X_train,columns=iris.feature_names)
X_train_panda.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -1.380249         -0.408183           3.686275          1.430746
1          -5.924972          0.601755         -12.472740         -5.133854
2           6.699259          2.621632          11.765783          6.480439
3           3.164474         -0.408183          10.250876          4.965531
4           0.134658          0.601755           5.201183          2.945654

### Training time (using Neural Networks)

- create your NN model with given structure (4 input neurons, 8 hidden neurons and 3 output neurons)
- use 'relu' activation in hidden layer 
- use softmax activation in output
- Compile your model using 'categorical_crossentropy' loss function and sgd optimizer
- Track the accuracy metric of the model

In [0]:
## Define the model
import keras
from keras.models import Sequential
from keras.layers import Dense,Activation,Input
model=Sequential()
model.add(Dense(10,input_dim=4,activation='relu'))
model.add(Dense(3,activation = 'softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [107]:
## Print the model summary
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 33        
Total params: 83
Trainable params: 83
Non-trainable params: 0
_________________________________________________________________


In [108]:
## Fit the model to data
model.fit(X_train,Yp_train,epochs=100)

Epoch 1/100
120/120 [==============================] - 0s 1ms/step - loss: 6.8253 - acc: 0.0000e+00
Epoch 2/100
120/120 [==============================] - 0s 60us/step - loss: 6.5851 - acc: 0.0000e+00
Epoch 3/100
120/120 [==============================] - 0s 81us/step - loss: 6.3334 - acc: 0.0000e+00
Epoch 4/100
120/120 [==============================] - 0s 61us/step - loss: 6.0854 - acc: 0.0083
Epoch 5/100
120/120 [==============================] - 0s 58us/step - loss: 5.8413 - acc: 0.0083
Epoch 6/100
120/120 [==============================] - 0s 94us/step - loss: 5.6070 - acc: 0.0167
Epoch 7/100
120/120 [==============================] - 0s 78us/step - loss: 5.3751 - acc: 0.0417
Epoch 8/100
120/120 [==============================] - 0s 63us/step - loss: 5.1546 - acc: 0.0417
Epoch 9/100
120/120 [==============================] - 0s 65us/step - loss: 4.9526 - acc: 0.0583
Epoch 10/100
120/120 [==============================] - 0s 66us/step - loss: 4.7448 - acc: 0.0833
Epoch 11/100
120/1

In [109]:
## Test the accuracy of the model on test data
mean_test,std_test=findstdmean(X_test)
X_test=normalizedX(X_test,mean_test,std_test)
def test_testData():
    assert Y_test.shape==(30,3)
    assert X_test.shape==(30,4)
#     mn, sn = findMeanStddev(X_test)
#     assert np.allclose(mn, np.zeros(2), atol=1)
#     assert np.allclose(sn, np.ones(2), atol=1)
    print("OK")
test_testData()
loss,accuracy=model.evaluate(X_test,Yp_test,verbose=0)# evaluate the model
Yp_predict=model.predict(X_test)
from sklearn.metrics import confusion_matrix
m=confusion_matrix(Yp_predict.argmax(axis=1),Yp_test.argmax(axis=1))

OK


### Confusion Matrix and Accuracy

In [110]:
### Lastly, report the accuracy of your model and print the Confusion Matrix
print("accuracy:%0.5f"%accuracy)
print(m)

accuracy:0.93333
[[ 9  0  0]
 [ 0 13  1]
 [ 0  1  6]]
