<a href="https://colab.research.google.com/github/sonudk/Source-Code-from-Tutorials/blob/master/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
#writing special matrices
m1=np.zeros((4,5))
m2=np.ones((3,6))
m3=np.eye(4)
m4=np.diag([1,234,4341,12313,1231,23,231,32,123,1,3,13])
print(m1)
print(m2)
print(m3)
print(m4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[    1     0     0     0     0     0     0     0     0     0     0     0]
 [    0   234     0     0     0     0     0     0     0     0     0     0]
 [    0     0  4341     0     0     0     0     0     0     0     0     0]
 [    0     0     0 12313     0     0     0     0     0     0     0     0]
 [    0     0     0     0  1231     0     0     0     0     0     0     0]
 [    0     0     0     0     0    23     0     0     0     0     0     0]
 [    0     0     0     0     0     0   231     0     0     0     0     0]
 [    0     0     0     0     0     0     0    32     0     0     0     0]
 [    0     0     0     0     0     0     0     0   123     0     0     0]
 [    0     0     0     0     0     0     0     0     0     1     0     0]
 [    0     0     0     0     0     0     0     0   

In [3]:
#indexing elements of Matrices
m1[3,2]

0.0

In [4]:
m4[4,4]

1231

In [5]:
m3[2,2]

1.0

In [6]:
#modifing terms
m4[4,4]=12312341
m4[4,4]

12312341

In [7]:
m4

array([[       1,        0,        0,        0,        0,        0,
               0,        0,        0,        0,        0,        0],
       [       0,      234,        0,        0,        0,        0,
               0,        0,        0,        0,        0,        0],
       [       0,        0,     4341,        0,        0,        0,
               0,        0,        0,        0,        0,        0],
       [       0,        0,        0,    12313,        0,        0,
               0,        0,        0,        0,        0,        0],
       [       0,        0,        0,        0, 12312341,        0,
               0,        0,        0,        0,        0,        0],
       [       0,        0,        0,        0,        0,       23,
               0,        0,        0,        0,        0,        0],
       [       0,        0,        0,        0,        0,        0,
             231,        0,        0,        0,        0,        0],
       [       0,        0,        0,    

In [8]:
#using random.random to get matrices elements are in range [0,1]
m5=np.random.random((3,2))
print(m5)
print(m5.T)

[[0.31982779 0.41268151]
 [0.20833195 0.62180124]
 [0.97118831 0.09023065]]
[[0.31982779 0.20833195 0.97118831]
 [0.41268151 0.62180124 0.09023065]]


In [11]:
m5[0,:]

array([0.31982779, 0.41268151])

In [12]:
m5[:,1]

array([0.41268151, 0.62180124, 0.09023065])

In [0]:
m6=np.random.random((2,3))

In [0]:
m7=m5+m6.T

In [15]:
print(m6)

[[0.17360288 0.1011226  0.06936951]
 [0.03049345 0.20278983 0.51420953]]


In [16]:
print(m7)

[[0.49343066 0.44317495]
 [0.30945455 0.82459107]
 [1.04055782 0.60444018]]


In [18]:
print(m5*m6.T)

[[0.05552302 0.01258408]
 [0.02106707 0.12609497]
 [0.06737086 0.04639746]]


In [21]:
print(m5.dot(m6))

[[0.06810711 0.11602943 0.23439106]
 [0.05512789 0.14716204 0.33418801]
 [0.17135253 0.11650694 0.11376832]]


In [22]:
print([np.concatenate((m5,m6.T),axis=0)])

[array([[0.31982779, 0.41268151],
       [0.20833195, 0.62180124],
       [0.97118831, 0.09023065],
       [0.17360288, 0.03049345],
       [0.1011226 , 0.20278983],
       [0.06936951, 0.51420953]])]


In [23]:
print([np.concatenate((m5,m6.T),axis=1)])

[array([[0.31982779, 0.41268151, 0.17360288, 0.03049345],
       [0.20833195, 0.62180124, 0.1011226 , 0.20278983],
       [0.97118831, 0.09023065, 0.06936951, 0.51420953]])]
