<a href="https://colab.research.google.com/github/sonudk/Source-Code-from-Tutorials/blob/master/using_chainer_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
m=np.ones((3,3))
m1=np.ones(3)
print(m,m1,(m-m1))
#import chainer

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [1. 1. 1.] [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
train,test=chainer.datasets.get_mnist()

In [3]:
print(len(train),type(train))
print(len(test),type(test))

60000 <class 'chainer.datasets.tuple_dataset.TupleDataset'>
10000 <class 'chainer.datasets.tuple_dataset.TupleDataset'>


In [5]:
print(len(train[0]),type(train[0]))

2 <class 'tuple'>


In [6]:
print(train[0])

(array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.    

In [7]:
print(train[0][0])

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

In [10]:
print(train[0].shape,train[0][0].shape)

NameError: ignored